import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Building2, Car, HeartHandshake, ShieldCheck } from "lucide-react";
import { useServerFn } from "@tanstack/react-start";
import { completeOnboarding, getWorkspace } from "@/lib/rescue.functions";
import { Brand } from "@/components/rescuerelay/brand";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export const Route=createFileRoute('/_authenticated/onboarding')({head:()=>({meta:[{title:'Choose your role — RescueRelay'},{name:'description',content:'Set up your RescueRelay donor, nonprofit, driver, or coordinator workspace.'},{property:'og:title',content:'Join the RescueRelay network'},{property:'og:description',content:'Choose how you will help move safe surplus food to the community.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary'}]}),component:Onboarding});
const roles=[['donor','Food donor','Post safe surplus in under a minute',Building2],['recipient','Nonprofit recipient','Accept food your organization can use',HeartHandshake],['driver','Volunteer driver','Pick up and document deliveries',Car],['coordinator','Coordinator','Verify partners and manage exceptions',ShieldCheck]] as const;
function Onboarding(){const navigate=useNavigate();const finish=useServerFn(completeOnboarding);const load=useServerFn(getWorkspace);const [name,setName]=useState('');const [role,setRole]=useState<(typeof roles)[number][0]>('donor');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const workspace=useQuery({queryKey:['rescue-workspace'],queryFn:()=>load(),refetchInterval:10000});useEffect(()=>{if(workspace.data?.roles.length)void navigate({to:'/dashboard',replace:true});if(workspace.error)setError('Account details could not load. Please try again.');},[workspace.data,workspace.error,navigate]);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const existing=await load();if(existing.roles.length){await navigate({to:'/dashboard',replace:true});return;}await finish({data:{fullName:name,role}});await navigate({to:'/dashboard',replace:true});}catch(err){setError(err instanceof Error?err.message:'Could not finish setup.');}finally{setBusy(false)}}return <div className="min-h-screen bg-muted/35"><header className="border-b bg-background px-5 py-5 md:px-10"><Brand/></header><main className="mx-auto max-w-4xl px-5 py-14"><p className="text-sm font-bold uppercase text-primary">Set up your workspace</p><h1 className="mt-3 text-4xl font-semibold">How will you help the relay?</h1><p className="mt-3 text-muted-foreground">Choose your primary role. Access is enforced for every rescue action.</p><form onSubmit={submit}><div className="mt-9"><Label htmlFor="name">Your full name</Label><Input id="name" className="mt-2 h-11 max-w-md" minLength={2} maxLength={100} required value={name} onChange={e=>setName(e.target.value)} placeholder="Jordan Lee"/></div><div className="mt-8 grid gap-3 md:grid-cols-2">{roles.map(([value,title,copy,Icon])=><Button variant="outline" key={value} type="button" aria-pressed={role===value} onClick={()=>setRole(value)} className={`h-auto min-h-32 justify-start whitespace-normal p-5 text-left transition ${role===value?'border-primary bg-primary/5 ring-1 ring-primary':'bg-background hover:border-primary/45'}`}><span className={`mr-2 grid size-10 shrink-0 place-items-center rounded-md ${role===value?'bg-primary text-primary-foreground':'bg-muted text-muted-foreground'}`}><Icon className="size-5"/></span><span><span className="font-semibold">{title}</span><span className="mt-1 block text-sm leading-6 text-muted-foreground">{copy}</span></span></Button>)}</div>{error&&<p role="alert" className="mt-5 rounded-md border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</p>}<Button className="mt-8 h-11 px-8" disabled={busy}>{busy?'Setting up…':'Enter RescueRelay'}</Button></form></main></div>}
