import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Building2, Car, HeartHandshake, Leaf, CheckCircle2, Clock3, MapPin, ShieldCheck, type LucideIcon } from "lucide-react";
import { useEffect } from 'react';
import { useNavigate } from '@tanstack/react-router';
import { usePartnerAuth } from '@/lib/auth-context';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Button } from "@/components/ui/button";
import { Brand } from "@/components/rescuerelay/brand";
import heroImage from "@/assets/rescuerelay-hero.jpg";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "RescueRelay — Surplus food, dispatched in minutes" },
    { name: "description", content: "RescueRelay matches surplus food with verified nonprofits and volunteer drivers before it spoils." },
    { property: "og:title", content: "RescueRelay — From surplus to supper" },
    { property: "og:description", content: "A coordinator-led dispatch network for urgent food rescue." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: HomePage,
});

function HomePage() {
  const { user, recovery } = usePartnerAuth();
  const navigate = useNavigate();
  useEffect(() => { if (recovery) void navigate({to:'/reset-password',replace:true}); }, [recovery,navigate]);
  return <div className="min-h-screen bg-background">
    <header className="absolute inset-x-0 top-0 z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8">
      <Brand inverse />
      <div className="flex items-center gap-5"><a href="#network" className="hidden text-sm font-medium text-background/85 md:block">The network</a><a href="#safety" className="hidden text-sm font-medium text-background/85 md:block">Food safety</a><Button asChild variant="secondary"><Link to="/dashboard">Explore live demo <ArrowRight /></Link></Button></div>
    </header>
    <section className="relative flex min-h-[86vh] items-end overflow-hidden bg-foreground text-background">
      <img src={heroImage} alt="A volunteer handing prepared meals to a nonprofit pantry worker" width={1600} height={1000} className="absolute inset-0 size-full object-cover object-center" />
      <div className="absolute inset-0 bg-hero-overlay" />
      <div className="relative z-10 mx-auto w-full max-w-7xl px-5 pb-14 pt-32 md:px-8 md:pb-20">
        <div className="max-w-3xl">
          <div className="mb-5 inline-flex items-center gap-2 border-l-2 border-signal pl-3 text-sm font-semibold text-background/85"><span className="size-2 animate-pulse rounded-full bg-signal" /> Live in Des Moines</div>
          <h1 className="max-w-2xl text-5xl font-semibold leading-[1.02] md:text-7xl">RescueRelay</h1>
          <p className="mt-4 max-w-xl text-3xl font-semibold leading-tight md:text-4xl">From surplus to supper—before it spoils.</p>
          <p className="mt-6 max-w-xl text-lg leading-8 text-background/80">RescueRelay gets every safe food donation to the right verified nonprofit and volunteer driver in minutes.</p>
          <div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link to="/dashboard">Start a rescue <ArrowRight /></Link></Button><Button asChild size="lg" variant="outline" className="border-background/35 bg-background/5 text-background hover:bg-background/15 hover:text-background"><a href="#network">Meet the network</a></Button></div>
        </div>
        <div className="mt-12 grid max-w-3xl grid-cols-3 gap-px overflow-hidden rounded-md border border-background/20 bg-background/20">
          {[['150 lb','featured pilot rescue'],['125','estimated meals'],['4 roles','one accountable relay']].map(([value,label]) => <div key={label} className="bg-foreground/70 p-4 backdrop-blur-sm md:p-5"><p className="text-xl font-semibold md:text-2xl">{value}</p><p className="mt-1 text-xs text-background/65 md:text-sm">{label}</p></div>)}
        </div>
      </div>
    </section>
    <section className="border-b bg-primary text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-8 md:grid-cols-4 md:px-8">{([[Clock3,'Urgency first','Ranked by time remaining'],[ShieldCheck,'Verified','Qualified recipient partners'],[MapPin,'Capacity-aware','Storage, distance, and need'],[CheckCircle2,'Documented','Every handoff recorded']] as Array<[LucideIcon,string,string]>).map(([Icon,title,copy]) => <div key={title} className="flex gap-3"><Icon className="mt-0.5 size-5 shrink-0 text-signal"/><div><p className="font-semibold">{title}</p><p className="text-sm text-primary-foreground/70">{copy}</p></div></div>)}</div></section>
    <section id="how-it-works" className="mx-auto max-w-7xl scroll-mt-8 px-5 py-20 md:px-8"><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold uppercase text-primary">One accountable relay</p><h2 className="mt-3 text-4xl font-semibold">No calling around. No lost handoffs.</h2></div><div className="grid gap-4 sm:grid-cols-3">{[['01','Post','A donor shares what is ready, where, and until when.'],['02','Match','Verified recipients are ranked by fit, need, and distance.'],['03','Deliver','A trained driver records pickup, safe transport, and delivery.']].map(([n,title,copy]) => <div key={n} className="border-t-2 border-primary pt-5"><span className="font-mono text-sm text-muted-foreground">{n}</span><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></div>)}</div></div></section>
    <section id="network" className="scroll-mt-8 border-y bg-muted/45"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase text-primary">The partner network</p><h2 className="mt-3 text-4xl font-semibold">Different roles. Shared purpose.</h2></div><p className="max-w-md text-sm leading-6 text-muted-foreground">Local businesses, community nonprofits, volunteers, and coordinators working together to keep good food in circulation.</p></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{([[Building2,'Food donors','Grocers, restaurants, and kitchens with safe surplus ready for pickup.'],[HeartHandshake,'Nonprofit recipients','Community partners accepting food that fits their storage and capacity.'],[Car,'Volunteer drivers','Available drivers moving food safely and recording each handoff.'],[ShieldCheck,'Coordinators','Partners overseeing verification, matches, and rescue exceptions.']] as Array<[LucideIcon,string,string]>).map(([Icon,title,copy])=><article key={title} className="rounded-md border bg-card p-6"><Icon className="size-7 text-primary"/><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p></article>)}</div><Button asChild variant="link" className="mt-6 px-0"><Link to={user?'/dashboard':'/auth'}>Find your place in the relay <ArrowRight/></Link></Button></div></section>
    <section id="safety" className="mx-auto grid max-w-7xl scroll-mt-8 gap-12 px-5 py-20 md:grid-cols-2 md:px-8"><div><ShieldCheck className="size-9 text-primary"/><p className="mt-6 text-sm font-bold uppercase text-primary">Safety before speed</p><h2 className="mt-3 text-4xl font-semibold">A good match is a safe match.</h2><p className="mt-5 max-w-lg leading-7 text-muted-foreground">Food rescue only works when partners can trust the handoff. Storage, capacity, food category, and pickup windows come before a match score.</p><p className="mt-4 text-sm leading-6 text-muted-foreground">RescueRelay supports your organization’s food-safety policy; it does not replace it.</p></div><div className="divide-y border-y">{[['Check the essentials','Record allergens, handling notes, required storage, and the pickup deadline before posting.'],['Match for real capacity','Only compatible recipients are ranked. Every Rescue Score includes a reason, not a black-box decision.'],['Keep the right to say no','Recipients can decline or flag unsafe food. Drivers must acknowledge safe handling before completing pickup.'],['Leave an accountable record','Donation, acceptance, assignment, pickup, and delivery are connected in one rescue history.']].map(([title,copy])=><div className="flex gap-4 py-6" key={title}><CheckCircle2 className="mt-1 size-5 shrink-0 text-success"/><div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></div></div>)}</div></section>
    <section id="impact" className="bg-primary text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 md:grid-cols-2 md:px-8"><div><Leaf className="size-8 text-signal"/><p className="mt-5 text-sm font-bold uppercase text-primary-foreground/65">Featured pilot scenario · illustrative</p><h2 className="mt-3 text-4xl font-semibold">One rescue. 125 possible meals.</h2><p className="mt-5 max-w-lg leading-7 text-primary-foreground/75">150 pounds of refrigerated meals travel from Capitol Fresh Market to Hope Community Pantry, with a recorded handoff at each stop.</p></div><div className="grid grid-cols-2 gap-8 self-center">{[['150 lb','food rescued'],['125','estimated meals'],['38 min','example delivery time'],['0 lb','example landfill waste']].map(([value,label])=><div key={label} className="border-t border-primary-foreground/25 pt-4"><p className="text-4xl font-semibold">{value}</p><p className="mt-2 text-sm text-primary-foreground/65">{label}</p></div>)}<p className="col-span-2 text-xs leading-5 text-primary-foreground/60">These are pilot-example figures, not network totals. Meal estimates use 1.2 lb per meal; actual results appear in your dashboard after delivery.</p></div></div></section>
    <section id="questions" className="mx-auto grid max-w-7xl scroll-mt-8 gap-10 px-5 py-20 md:grid-cols-[.8fr_1.2fr] md:px-8"><div><p className="text-sm font-bold uppercase text-primary">Before you join</p><h2 className="mt-3 text-4xl font-semibold">A few essentials.</h2></div><Accordion type="single" collapsible>{[['Who can participate?','Food donors, nonprofit recipients, volunteer drivers, and coordinators can create an account. Organization verification and access requirements apply before operational actions.'],['How are recipients selected?','Eligible recipients are ranked using an explainable Rescue Score based on urgency, distance, capacity, category compatibility, storage, and community need. Coordinators and recipients remain part of the decision.'],['What happens if food is unsafe?','Do not accept or transport unsafe food. A recipient can flag a proposed match as unsafe, and all partners should follow their organization’s food-safety policy.'],['Where is the pilot based?','The featured RescueRelay pilot network is based in Des Moines, Iowa. The displayed sample rescue is illustrative, and your signed-in dashboard shows saved records.'],['How is impact measured?','Completed donations contribute their recorded weight to rescued-food totals. Estimated meals are calculated at 1.2 lb per meal; delivery timestamps provide the actual handoff duration.']].map(([q,a],i)=><AccordionItem key={q} value={String(i)}><AccordionTrigger className="py-5 text-base">{q}</AccordionTrigger><AccordionContent className="leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></section>
    <section className="border-t bg-accent"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 px-5 py-12 md:flex-row md:items-center md:px-8"><div><h2 className="text-3xl font-semibold">Good food deserves a next stop.</h2><p className="mt-3 text-muted-foreground">Be part of the next accountable rescue.</p></div><Button asChild size="lg"><Link to="/dashboard">Explore live workspace <ArrowRight/></Link></Button></div></section>
    <footer className="bg-foreground text-background"><div className="mx-auto max-w-7xl px-5 py-12 md:px-8"><div className="grid gap-10 md:grid-cols-[2fr_1fr_1fr]"><div><Brand inverse/><p className="mt-5 max-w-sm text-sm leading-6 text-background/60">Safe surplus. Local partners. One accountable relay.</p><p className="mt-4 flex items-center gap-2 text-xs text-background/60"><MapPin className="size-4"/> Des Moines, Iowa · pilot network</p></div><nav aria-label="About RescueRelay" className="flex flex-col gap-3 text-sm"><p className="mb-1 font-semibold">The relay</p><a href="#how-it-works" className="text-background/65 hover:text-background">How it works</a><a href="#network" className="text-background/65 hover:text-background">Partner network</a><a href="#impact" className="text-background/65 hover:text-background">Pilot impact</a></nav><nav aria-label="Partner resources" className="flex flex-col gap-3 text-sm"><p className="mb-1 font-semibold">Partner essentials</p><a href="#safety" className="text-background/65 hover:text-background">Food safety</a><a href="#questions" className="text-background/65 hover:text-background">Common questions</a><Link to="/dashboard" className="text-background/65 hover:text-background">Live command center</Link></nav></div><div className="mt-10 flex flex-wrap justify-between gap-3 border-t border-background/15 pt-6 text-xs text-background/50"><p>© 2026 RescueRelay</p><p>Meal estimates are not a guarantee of servings.</p></div></div></footer>
  </div>
}
